package com.uon.uonwams.configs;

public enum State {
    LOGIN,
    FORGOT_PASSWORD,
    HOME,
    MY_WORKLOAD,
    VIEW_USERS,
    ADD_USER,
    EDIT_USER,
    DELETE_USER,
    VIEW_USER_WORKLOAD,
    VIEW_WORKLOAD,
    ADD_ACTIVITY,
    EDIT_ACTIVITY,
    DELETE_ACTIVITY,
    VIEW_PROFILE,
    EDIT_PROFILE,
    CHANGE_PASSWORD_PROFILE
}
